kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-linode-controller
  namespace: kube-system
  labels:
    app: csi-linode-controller
spec:
  serviceName: "csi-linode"
  replicas: 1
  selector:
    matchLabels:
      app: csi-linode-controller
  template:
    metadata:
      labels:
        app: csi-linode-controller
        role: csi-linode
    spec:
      serviceAccount: csi-controller-sa
      initContainers:
        - name: init
          image: bitnami/kubectl:1.16.3-debian-10-r36
          command:
            - /scripts/get-linode-id.sh
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
          - name: linode-info
            mountPath: /linode-info
          - name: get-linode-id
            mountPath: /scripts
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.1.0
          imagePullPolicy: IfNotPresent
          args:
            - "--default-fstype=ext4"
            - "--volume-name-prefix=pvc"
            - "--volume-name-uuid-length=16"
            - "--csi-address=$(ADDRESS)"
            - "--v=2"
            - "--metrics-address=0.0.0.0:10248"
          ports:
            - name: metrics
              containerPort: 10248
              protocol: TCP
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.7.0
          imagePullPolicy: IfNotPresent
          args:
            - "--v=2"
            - "--csi-address=$(ADDRESS)"
            - "--metrics-address=0.0.0.0:10249"
          ports:
            - name: metrics
              containerPort: 10249
              protocol: TCP
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.12.0
          imagePullPolicy: IfNotPresent
          args:
          - "--v=2"
          - "--csi-address=$(ADDRESS)"
          - "--metrics-address=0.0.0.0:10250"
          ports:
            - name: metrics
              containerPort: 10250
              protocol: TCP
          env:
          - name: ADDRESS
            value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
          - name: socket-dir
            mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-linode-plugin
          image: linode/linode-blockstorage-csi-driver:latest
          args:
            - "--v=2"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: LINODE_URL
              value: https://api.linode.com/v4
            - name: LINODE_BS_PREFIX
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: LINODE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: linode
                  key: token
          volumeMounts:
            - name: linode-info
              mountPath: /linode-info
            - name: get-linode-id
              mountPath: /scripts
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: linode-info
          emptyDir: {}
        - name: get-linode-id
          configMap:
            name: get-linode-id
            # octal mode 755
            defaultMode: 493
