# Secrets:
# apiToken [Required if secretRef is not set] - Must be a Linode APIv4 Personal Access Token with all permissions. (https://cloud.linode.com/profile/tokens)
apiToken: ""

# region [Required if secretRef is not set] - Must be a Linode region. (https://api.linode.com/v4/regions)
region: ""

# Default namespace is "kube-system" but it can be set to another namespace
namespace: kube-system

# Set these values if your APIToken and region are already present in a k8s secret.
# secretRef:
#   name: "linode"
#   apiTokenRef: "apiToken"
#   regionRef: "region"

# Default storageClass is "linode-block-storage-retain" but it can be set to
# "linode-block-storage" or left as an empty string
defaultStorageClass: linode-block-storage-retain

# Images - Default 
csiProvisioner:
  image: registry.k8s.io/sig-storage/csi-provisioner
  tag: v3.0.0
  pullPolicy: IfNotPresent

csiAttacher:
  image: registry.k8s.io/sig-storage/csi-attacher
  tag: v3.3.0
  pullPolicy: IfNotPresent

csiResizer:
  image: registry.k8s.io/sig-storage/csi-resizer
  tag: v1.3.0
  pullPolicy: IfNotPresent

csiLinodePlugin:
  image: linode/linode-blockstorage-csi-driver 
  tag: v0.5.3
  pullPolicy: IfNotPresent

kubectl:
  image: alpine/k8s # This needs to be alpine based and have both kubectl and curl installed.
  tag: 1.25.14

csiNodeDriverRegistrar:
  image: registry.k8s.io/sig-storage/csi-node-driver-registrar
  tag: v1.3.0
