# Secrets:
# apiToken [Required if secretRef is not set] - Must be a Linode APIv4 Personal Access Token with all permissions. (https://cloud.linode.com/profile/tokens)
apiToken: ""

# region [Required if secretRef is not set] - Must be a Linode region. (https://api.linode.com/v4/regions)
region: ""

# (OPTIONAL) Label prefix for the Linode Block Storage volumes created by this driver.
volumeLabelPrefix: ""

# Default namespace is "kube-system" but it can be set to another namespace
namespace: kube-system

# Set these values if your APIToken and region are already present in a k8s secret.
# secretRef:
#   name: "linode"
#   apiTokenRef: "apiToken"
#   regionRef: "region"

# Default storageClass is "linode-block-storage-retain" but it can be set to
# "linode-block-storage" or left as an empty string
defaultStorageClass: linode-block-storage-retain

# set these value to a comma separated string if you'd like to add tags to the created volumes
# volumeTags:
#  - example
#  - test

# Images - Default
csiProvisioner:
  image: registry.k8s.io/sig-storage/csi-provisioner
  tag: v5.1.0
  pullPolicy: IfNotPresent
  metrics:
    address: "0.0.0.0:10248"
    port: 10248  # Metrics port for csi-provisioner

csiAttacher:
  image: registry.k8s.io/sig-storage/csi-attacher
  tag: v4.7.0
  pullPolicy: IfNotPresent
  metrics:
    address: "0.0.0.0:10249"
    port: 10249  # Metrics port for csi-attacher

csiResizer:
  image: registry.k8s.io/sig-storage/csi-resizer
  tag: v1.12.0
  pullPolicy: IfNotPresent
  metrics:
    address: "0.0.0.0:10250"
    port: 10250  # Metrics port for csi-resizer

csiLinodePlugin:
  image: linode/linode-blockstorage-csi-driver
  tag:  # only set if required, defaults to .Chart.AppVersion set during release or "latest" by default
  pullPolicy: IfNotPresent
  podsMountDir: /var/lib/kubelet

kubectl:
  image: alpine/k8s  # This needs to be alpine based and have both kubectl and curl installed.
  tag: 1.25.14

csiNodeDriverRegistrar:
  image: registry.k8s.io/sig-storage/csi-node-driver-registrar
  tag: v2.12.0
