# needed for StatefulSet
kind: Service
apiVersion: v1
metadata:
  name: csi-provisioner-linodeplugin
  labels:
    app: csi-provisioner-linodeplugin
spec:
  selector:
    app: csi-provisioner-linodeplugin
  ports:
    - name: dummy
      port: 12345
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-provisioner-linodeplugin
spec:
  serviceName: "csi-provisioner-linodeplugin"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-provisioner-linodeplugin
    spec:
      serviceAccount: csi-provisioner
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v0.2.0
          args:
            - "--provisioner=com.linode.csi.linodebs"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: linode-csi-plugin
          image: displague/linode-csi-plugin:v0.0.1
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--token=$(LINODE_ACCESS_TOKEN)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: LINODE_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: linodetoken
                  key: token
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}
